import type { Homepage, StoreSettings } from "@/types";
export const defaultStore: StoreSettings = {
  id: 1,
  business_name: "Achu Designer Boutique",
  whatsapp_number: "",
  phone_number: "",
  instagram_url: "",
  email: "",
  address: "",
  maps_url: "",
  map_embed_url: "",
  opening_hours: "",
  currency: "INR",
  low_stock_threshold: 3,
  about_heading: "A little tradition. A little you.",
  about_story:
    "Add your boutique’s story in Store Settings. Share the people, ideas, and craft behind Achu Designer Boutique.",
  about_philosophy: "Add your collection philosophy in Store Settings.",
  size_guide: [],
};
export const defaultHomepage: Homepage = {
  id: 1,
  hero_image: "",
  hero_mobile_image: "",
  hero_heading: "Elegance,\nin every detail.",
  hero_subtitle:
    "Discover a thoughtful edit of Indian wear. For the everyday, the extraordinary, and everything in between.",
  hero_enabled: true,
  primary_text: "Explore the collection",
  primary_url: "/shop",
  secondary_text: "Discover new arrivals",
  secondary_url: "/shop?new=true",
  featured_collection_id: "",
  featured_title: "Made for memorable moments.",
  featured_description: "Explore our occasion edit.",
  featured_image: "",
  promo_image: "",
  promo_heading: "Your next occasion,\nyour own expression.",
  promo_subtitle:
    "Discover the collection and find a piece that feels like you.",
  promo_text: "Discover the edit",
  promo_url: "/collections",
  show_categories: true,
  show_new_arrivals: true,
  show_featured: true,
  show_best_sellers: true,
  show_promo: true,
  show_instagram: true,
  show_store: true,
};
