export type Variant = {
  id: string;
  product_id: string;
  size: string;
  stock_quantity: number;
  active: boolean;
  sku?: string;
};
export type ProductImage = {
  id?: string;
  storage_path: string;
  alt_text: string;
  sort_order: number;
  is_cover: boolean;
};
export type Taxonomy = {
  id: string;
  name: string;
  slug: string;
  description: string;
  image: string;
  active: boolean;
  display_order: number;
  featured?: boolean;
};
export type Product = {
  id: string;
  name: string;
  slug: string;
  category_id: string;
  short_description: string;
  description: string;
  fabric: string;
  colour: string;
  care_instructions: string;
  sku: string;
  selling_price: number;
  original_price: number | null;
  status: "draft" | "active" | "hidden";
  is_featured: boolean;
  is_new_arrival: boolean;
  is_best_seller: boolean;
  keywords: string;
  meta_title: string;
  meta_description: string;
  created_at: string;
  updated_at?: string;
  product_images: ProductImage[];
  product_variants: Variant[];
  product_collections: { collection_id: string }[];
  categories?: { name: string; slug: string };
  sample?: boolean;
};
export type StoreSettings = {
  id: number;
  business_name: string;
  whatsapp_number: string;
  phone_number: string;
  instagram_url: string;
  email: string;
  address: string;
  maps_url: string;
  map_embed_url: string;
  opening_hours: string;
  currency: string;
  low_stock_threshold: number;
  about_heading: string;
  about_story: string;
  about_philosophy: string;
  size_guide: {
    size: string;
    bust: string;
    waist: string;
    hip: string;
    length: string;
  }[];
};
export type Homepage = {
  id: number;
  hero_image: string;
  hero_mobile_image: string;
  hero_heading: string;
  hero_subtitle: string;
  hero_enabled: boolean;
  primary_text: string;
  primary_url: string;
  secondary_text: string;
  secondary_url: string;
  featured_collection_id: string;
  featured_title: string;
  featured_description: string;
  featured_image: string;
  promo_image: string;
  promo_heading: string;
  promo_subtitle: string;
  promo_text: string;
  promo_url: string;
  show_categories: boolean;
  show_new_arrivals: boolean;
  show_featured: boolean;
  show_best_sellers: boolean;
  show_promo: boolean;
  show_instagram: boolean;
  show_store: boolean;
};
export type Policy = {
  id: string;
  slug: string;
  title: string;
  content: string;
};
export type Enquiry = {
  id: string;
  order_reference: string;
  customer_name: string;
  phone: string;
  alternate_phone: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
  landmark: string;
  customer_note: string;
  subtotal: number;
  status: "new" | "contacted" | "confirmed" | "cancelled" | "completed";
  created_at: string;
  order_enquiry_items: {
    product_name_snapshot: string;
    size_snapshot: string;
    quantity: number;
    unit_price_snapshot: number;
    subtotal_snapshot: number;
  }[];
};
